### ISSUE TITLE
General build script

### ISSUE THREAD

**Issue by jeroen** [JanMarvin/v8-static#1]
I like the monolith, I haven't been able to build a static monolith myself yet. Would it possible to convert the PKGBUILD into a generic bash script, so that we can build static monoliths automatically for various platforms?

**Comment by JanMarvin** [comment]
sure, that should be possible. I'll look into it

**Comment by jeroen** [comment]
I started experimenting with scripting into a dockerfile to automatically build on GHA: https://github.com/jeroen/build-v8-static

Thanks for your great example code!

**Comment by JanMarvin** [comment]
Just a follow up since you apparently have already sorted it out. I started poking around to create a bash only build script here https://github.com/JanMarvin/v8-static/commit/449ea8d854480605452ebea5be7a074a0b251517

**Comment by JanMarvin** [comment]
You might want to have a look at the following lines. Not sure how they handle cross compiles, but might be worth looking in if you want to support multiple architectures
https://github.com/JanMarvin/v8-static/blob/449ea8d854480605452ebea5be7a074a0b251517/build.sh#L86-L89

**Comment by jeroen** [comment]
Thanks, yes there is still much to improve. Also, I think if the script should be future-proof, we need to checkout a fixed version of depot_tools ?

By the way, did you run into the issue that the build script requires glib-devel? I had to install that on centos, I don't understand why.

**Comment by JanMarvin** [comment]
> Thanks, yes there is still much to improve. Also, I think if the script should be future-proof, we need to checkout a fixed version of depot_tools ?

That should be no problem, though I don't think depot tools has changed that much lately. The biggest internal change was the switch to python3, but the commands we use (fetch, gclient, gn, ninja) have been stable for a while.

> By the way, did you run into the issue that the build script requires glib-devel? I had to install that on centos, I don't understand why.

Arch does not have devel packages, either you have the entire glib or none. Maybe some header files were missing.
